/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package longhm.common.thrift;


import org.apache.thrift.TEnum;

public enum ReturnCode implements org.apache.thrift.TEnum {
  UNKNOWN_ERROR(-1),
  ILLEGAL_ARGUMENT(-2),
  SUCCESS(0),
  NOT_FOUND(1);

  private final int value;

  private ReturnCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ReturnCode findByValue(int value) { 
    switch (value) {
      case -1:
        return UNKNOWN_ERROR;
      case -2:
        return ILLEGAL_ARGUMENT;
      case 0:
        return SUCCESS;
      case 1:
        return NOT_FOUND;
      default:
        return null;
    }
  }
}
