/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package longhm.dal.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-05-24")
public class MultiProfileAttributeResult implements org.apache.thrift.TBase<MultiProfileAttributeResult, MultiProfileAttributeResult._Fields>, java.io.Serializable, Cloneable, Comparable<MultiProfileAttributeResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MultiProfileAttributeResult");

  private static final org.apache.thrift.protocol.TField RETURN_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("ReturnCode", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField PROFILE_ATTRS_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("profileAttrsList", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MultiProfileAttributeResultStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MultiProfileAttributeResultTupleSchemeFactory());
  }

  /**
   * 
   * @see longhm.common.thrift.ReturnCode
   */
  public longhm.common.thrift.ReturnCode ReturnCode; // required
  public List<ProfileAttribute> profileAttrsList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see longhm.common.thrift.ReturnCode
     */
    RETURN_CODE((short)1, "ReturnCode"),
    PROFILE_ATTRS_LIST((short)2, "profileAttrsList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RETURN_CODE
          return RETURN_CODE;
        case 2: // PROFILE_ATTRS_LIST
          return PROFILE_ATTRS_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RETURN_CODE, new org.apache.thrift.meta_data.FieldMetaData("ReturnCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, longhm.common.thrift.ReturnCode.class)));
    tmpMap.put(_Fields.PROFILE_ATTRS_LIST, new org.apache.thrift.meta_data.FieldMetaData("profileAttrsList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ProfileAttribute.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MultiProfileAttributeResult.class, metaDataMap);
  }

  public MultiProfileAttributeResult() {
  }

  public MultiProfileAttributeResult(
    longhm.common.thrift.ReturnCode ReturnCode,
    List<ProfileAttribute> profileAttrsList)
  {
    this();
    this.ReturnCode = ReturnCode;
    this.profileAttrsList = profileAttrsList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MultiProfileAttributeResult(MultiProfileAttributeResult other) {
    if (other.isSetReturnCode()) {
      this.ReturnCode = other.ReturnCode;
    }
    if (other.isSetProfileAttrsList()) {
      List<ProfileAttribute> __this__profileAttrsList = new ArrayList<ProfileAttribute>(other.profileAttrsList.size());
      for (ProfileAttribute other_element : other.profileAttrsList) {
        __this__profileAttrsList.add(new ProfileAttribute(other_element));
      }
      this.profileAttrsList = __this__profileAttrsList;
    }
  }

  public MultiProfileAttributeResult deepCopy() {
    return new MultiProfileAttributeResult(this);
  }

  @Override
  public void clear() {
    this.ReturnCode = null;
    this.profileAttrsList = null;
  }

  /**
   * 
   * @see longhm.common.thrift.ReturnCode
   */
  public longhm.common.thrift.ReturnCode getReturnCode() {
    return this.ReturnCode;
  }

  /**
   * 
   * @see longhm.common.thrift.ReturnCode
   */
  public MultiProfileAttributeResult setReturnCode(longhm.common.thrift.ReturnCode ReturnCode) {
    this.ReturnCode = ReturnCode;
    return this;
  }

  public void unsetReturnCode() {
    this.ReturnCode = null;
  }

  /** Returns true if field ReturnCode is set (has been assigned a value) and false otherwise */
  public boolean isSetReturnCode() {
    return this.ReturnCode != null;
  }

  public void setReturnCodeIsSet(boolean value) {
    if (!value) {
      this.ReturnCode = null;
    }
  }

  public int getProfileAttrsListSize() {
    return (this.profileAttrsList == null) ? 0 : this.profileAttrsList.size();
  }

  public java.util.Iterator<ProfileAttribute> getProfileAttrsListIterator() {
    return (this.profileAttrsList == null) ? null : this.profileAttrsList.iterator();
  }

  public void addToProfileAttrsList(ProfileAttribute elem) {
    if (this.profileAttrsList == null) {
      this.profileAttrsList = new ArrayList<ProfileAttribute>();
    }
    this.profileAttrsList.add(elem);
  }

  public List<ProfileAttribute> getProfileAttrsList() {
    return this.profileAttrsList;
  }

  public MultiProfileAttributeResult setProfileAttrsList(List<ProfileAttribute> profileAttrsList) {
    this.profileAttrsList = profileAttrsList;
    return this;
  }

  public void unsetProfileAttrsList() {
    this.profileAttrsList = null;
  }

  /** Returns true if field profileAttrsList is set (has been assigned a value) and false otherwise */
  public boolean isSetProfileAttrsList() {
    return this.profileAttrsList != null;
  }

  public void setProfileAttrsListIsSet(boolean value) {
    if (!value) {
      this.profileAttrsList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RETURN_CODE:
      if (value == null) {
        unsetReturnCode();
      } else {
        setReturnCode((longhm.common.thrift.ReturnCode)value);
      }
      break;

    case PROFILE_ATTRS_LIST:
      if (value == null) {
        unsetProfileAttrsList();
      } else {
        setProfileAttrsList((List<ProfileAttribute>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RETURN_CODE:
      return getReturnCode();

    case PROFILE_ATTRS_LIST:
      return getProfileAttrsList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RETURN_CODE:
      return isSetReturnCode();
    case PROFILE_ATTRS_LIST:
      return isSetProfileAttrsList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MultiProfileAttributeResult)
      return this.equals((MultiProfileAttributeResult)that);
    return false;
  }

  public boolean equals(MultiProfileAttributeResult that) {
    if (that == null)
      return false;

    boolean this_present_ReturnCode = true && this.isSetReturnCode();
    boolean that_present_ReturnCode = true && that.isSetReturnCode();
    if (this_present_ReturnCode || that_present_ReturnCode) {
      if (!(this_present_ReturnCode && that_present_ReturnCode))
        return false;
      if (!this.ReturnCode.equals(that.ReturnCode))
        return false;
    }

    boolean this_present_profileAttrsList = true && this.isSetProfileAttrsList();
    boolean that_present_profileAttrsList = true && that.isSetProfileAttrsList();
    if (this_present_profileAttrsList || that_present_profileAttrsList) {
      if (!(this_present_profileAttrsList && that_present_profileAttrsList))
        return false;
      if (!this.profileAttrsList.equals(that.profileAttrsList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_ReturnCode = true && (isSetReturnCode());
    list.add(present_ReturnCode);
    if (present_ReturnCode)
      list.add(ReturnCode.getValue());

    boolean present_profileAttrsList = true && (isSetProfileAttrsList());
    list.add(present_profileAttrsList);
    if (present_profileAttrsList)
      list.add(profileAttrsList);

    return list.hashCode();
  }

  @Override
  public int compareTo(MultiProfileAttributeResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetReturnCode()).compareTo(other.isSetReturnCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReturnCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ReturnCode, other.ReturnCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProfileAttrsList()).compareTo(other.isSetProfileAttrsList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProfileAttrsList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.profileAttrsList, other.profileAttrsList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MultiProfileAttributeResult(");
    boolean first = true;

    sb.append("ReturnCode:");
    if (this.ReturnCode == null) {
      sb.append("null");
    } else {
      sb.append(this.ReturnCode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("profileAttrsList:");
    if (this.profileAttrsList == null) {
      sb.append("null");
    } else {
      sb.append(this.profileAttrsList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MultiProfileAttributeResultStandardSchemeFactory implements SchemeFactory {
    public MultiProfileAttributeResultStandardScheme getScheme() {
      return new MultiProfileAttributeResultStandardScheme();
    }
  }

  private static class MultiProfileAttributeResultStandardScheme extends StandardScheme<MultiProfileAttributeResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MultiProfileAttributeResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RETURN_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.ReturnCode = longhm.common.thrift.ReturnCode.findByValue(iprot.readI32());
              struct.setReturnCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PROFILE_ATTRS_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list20 = iprot.readListBegin();
                struct.profileAttrsList = new ArrayList<ProfileAttribute>(_list20.size);
                ProfileAttribute _elem21;
                for (int _i22 = 0; _i22 < _list20.size; ++_i22)
                {
                  _elem21 = new ProfileAttribute();
                  _elem21.read(iprot);
                  struct.profileAttrsList.add(_elem21);
                }
                iprot.readListEnd();
              }
              struct.setProfileAttrsListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MultiProfileAttributeResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.ReturnCode != null) {
        oprot.writeFieldBegin(RETURN_CODE_FIELD_DESC);
        oprot.writeI32(struct.ReturnCode.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.profileAttrsList != null) {
        oprot.writeFieldBegin(PROFILE_ATTRS_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.profileAttrsList.size()));
          for (ProfileAttribute _iter23 : struct.profileAttrsList)
          {
            _iter23.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MultiProfileAttributeResultTupleSchemeFactory implements SchemeFactory {
    public MultiProfileAttributeResultTupleScheme getScheme() {
      return new MultiProfileAttributeResultTupleScheme();
    }
  }

  private static class MultiProfileAttributeResultTupleScheme extends TupleScheme<MultiProfileAttributeResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MultiProfileAttributeResult struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetReturnCode()) {
        optionals.set(0);
      }
      if (struct.isSetProfileAttrsList()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetReturnCode()) {
        oprot.writeI32(struct.ReturnCode.getValue());
      }
      if (struct.isSetProfileAttrsList()) {
        {
          oprot.writeI32(struct.profileAttrsList.size());
          for (ProfileAttribute _iter24 : struct.profileAttrsList)
          {
            _iter24.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MultiProfileAttributeResult struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.ReturnCode = longhm.common.thrift.ReturnCode.findByValue(iprot.readI32());
        struct.setReturnCodeIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list25 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.profileAttrsList = new ArrayList<ProfileAttribute>(_list25.size);
          ProfileAttribute _elem26;
          for (int _i27 = 0; _i27 < _list25.size; ++_i27)
          {
            _elem26 = new ProfileAttribute();
            _elem26.read(iprot);
            struct.profileAttrsList.add(_elem26);
          }
        }
        struct.setProfileAttrsListIsSet(true);
      }
    }
  }

}

